name: Terraform networking deletion

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform networking deletion
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"
      TF_ACTION_WORKING_DIR: "./networking"

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_ACTION_WORKING_DIR }}

      # Step 7: Terraform Apply
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TF_ACTION_WORKING_DIR }}
